### PR TITLE
DC-587 Implement list style for landing page

### PR DESCRIPTION
**Pull request by eltesoro-koji**
Added classes to implement cards.
Updated quickstart.adoc (tutorial intro) with the new classes.

### CODE REVIEW

**Review by rasienko — CHANGES_REQUESTED** [review]
This looks cool! A few notes:

- Add a bit more padding at the top of the card. The title text is too close to the card border. Maybe 10px?
- Address text overflow. This happens in mobile view tests:
image
We probably want to truncate the text that doesn't fit.
- Add more space after the bottom of the cards section. The subsequent h2 is too close to the bottom. It looks like the clearfloat style might be a contributor. 
image

**Comment by eltesoro-koji** [comment]
>     * Add a bit more padding at the top of the card. The title text is too close to the card border. Maybe 10px?
Changed it to 20px, which looks better.

>     * Address text overflow. This happens in mobile view tests:
>       We probably want to truncate the text that doesn't fit.
Added *overflow: auto*. However, I can't find a solution for it to keep the padding, so the scrolling (and text) goes right to the top edge and bottom edge.

I also set a *min-width* so the card doesn't get too narrow.

>     * Add more space after the bottom of the cards section. The subsequent h2 is too close to the bottom. It looks like the clearfloat style might be a contributor.
It doesn't look like the *clearfloat* has any effect on the margin/padding until I added "{blank}" that it can apply the margin to. (I decided against changing the H2 styling because that affects everything.)

**Review by rasienko — APPROVED** [review]
Looks great! We have a few pages that could use these styles (namely, the landing pages for local development and the two game app examples). We can merge this now and add those as another PR, or add them to this PR. Your choice :)

**Comment by eltesoro-koji** [comment]
Also updated with the new card style:
* src/asciidoc/docs/getting-started/developer.adoc
* src/asciidoc/docs/guides-general/game-iap/intro.adoc
* src/asciidoc/docs/guides-general/game-tutorial/intro.adoc

I also created a new class for the card height only so we could have flexibility in avoiding too many scrollbars or too big spaces at the bottom of the card.

**Review by rasienko — CHANGES_REQUESTED** [review]
Left to do:
- Add card styles to: docs/develop/local-development
- Avoid scroll bars on docs/getting-started/developer.adoc. Either remove cards and revert this page to a description list or we need to rethink the card styles in this context. I'd lean toward reverting, since the cards were intended for the tutorial landing pages, and this page was not written or designed with that intention. Ideally, we'd have a more stylized home page for the developer site and this page would look more like a docs page.

Looks good:
- docs/guides-general/game-iap/intro.adoc
- docs/guides-general/game-tutorial/intro.adoc

**Comment by eltesoro-koji** [comment]
* Restored getting-started/developer.adoc. 
* Added card styling to develop/local-development/localDevelopment.adoc.

**Review by rasienko — APPROVED** [review]
Looks good! The local development tutorial was missing the section numbers, so I added them. Everything should be ready to merge when you are :)

**Comment by eltesoro-koji** [comment]
Thanks, Rachel!

**Pull request merged**
