### PR TITLE
Style updates

### PR DESCRIPTION
**Pull request by arist0tl3**

### CODE REVIEW

**Comment by arist0tl3** [comment]
@rasienko 

I think this covers the first batch of updates.

**Comment by rasienko** [comment]
@arist0tl3 Thanks! A few thoughts/questions...

- We weren't going to remove the footer in this round because we don't have a new location identified for the links. Can we add it back but make sure the styles match the new styles? (e.g. same gray, maybe smaller font sizes to match the sidebar nav)
- The top nav font is too light. Can we match the sidebar nav headings?
- Had a thought about the header styling. What do you think of removing the box shadow and replacing it with a simple border-bottom that matches the sidebar nav?

**Comment by arist0tl3** [comment]
@rasienko 

- I can put the footer back but it looks quite janky on the redirect bc the home page loads with no content and then the client-side redirect happens. I could just make a full-screen white background to push the footer offscreen?

- I can make it darker but without a hover effect?

- I think that could work but still wouldn't match the koji header?

**Comment by rasienko** [comment]
@arist0tl3 per our conversation, we agreed to:

- Add a white page to push down the footer, to avoid the "janky" on the home page redirect.
- Use the darker color for the regular state and the current, lighter color for the header state.
- Keep the header as is until we have more info about the desired outcomes.

**Comment by arist0tl3** [comment]
@rasienko 

Gonna close this and open a new PR as the changes aren't really aligned.

**Pull request closed without merging**
