### PR TITLE
Package reference for Koji in-app purchases

### PR DESCRIPTION
**Pull request by rasienko**
@anderjason here is the first draft of the in-app purchase reference docs. Please review and let me know what changes are required. Thanks!

cc:// @arist0tl3

### CODE REVIEW

**Comment by rasienko** [comment]
Hi @sthielen, can you please review this draft of the reference docs for the IAP package? Also, here are a few questions that @anderjason and I weren’t sure about:

- What does the project token represent?
- Is a user token always unique to a user, or could a user have more than one token?
- In getToken, what is forceRefresh and what are the use cases for it?
- What is updateReceipts and what are the use cases for it? I took a guess as to how/why this method might be used. Can you please check it out and also check the example?
- Can you please validate the structure and property descriptions for the IapReceipt object? Jason had obtained this model through testing, but wasn’t sure whether all of the fields were standard and/or required. For example, if a value isn’t set, is the field returned as empty or null?

**Comment by sthielen** [comment]
Yay!

> * What does the project token represent?

The project token is the Koji's secret key. It is available as an environment variable at runtime as `process.env.KOJI_PROJECT_TOKEN` - it's the same one as used by `koji-database-sdk`. See [here](https://withkoji.com/templates/sean/donation/code#backend%2Fsrc%2Froutes.js) for a sample implementation.

> * Is a user token always unique to a user, or could a user have more than one token?

The user token is a short-lived token and expires at the end of the user's session with a particular Koji. A user token is created when a logged-in user loads a Koji, and destroyed when the user closes the Koji. When the user revisits a Koji, they will have a different token. Tokens are specific to a user and a Koji, so the same user will send different tokens to different Kojis. This is why the pairing of user token and "project token" are necessary to resolve purchases for a given user.

> * In getToken, what is forceRefresh and what are the use cases for it?

`forceRefresh` forces the Koji to ask for a new token, instead of using the cached one. This parameter can be ignored today, but may be used in the future.

> * What is updateReceipts and what are the use cases for it? I took a guess as to how/why this method might be used. Can you please check it out and also check the example?

Your guess is correct. `updateReceipts` can be used to store additional key/value pairs on the item receipt. An example might be if the user is purchasing a "power up" - when the user uses the power up in the game, the developer can update the receipt to show that the product has been consumed and should not be available for future sessions (e.g., by doing something like `updateReceipt('RECEIPT_ID', { isConsumed: true })`).

> * Can you please validate the structure and property descriptions for the IapReceipt object? Jason had obtained this model through testing, but wasn’t sure whether all of the fields were standard and/or required. For example, if a value isn’t set, is the field returned as empty or null?

The structure of the receipt object is:
```
interface IapReceipt {
  id: string;
  userId: string; // `userId` will always be "unavailable", as Kojis are required to interact with users via the short-lived token so as to avoid leaking/fingerprinting users at a global level
  productId: string;
  purchasedPrice: number;
  attributes: {[index: string]: any};
  datePurchased: Date;
  product: {
    id: string;
    appId: string;
    ownerUserId: string;
    price: number;
    priceIsUnset: boolean;
    isConsumable: boolean;
    name: string;
    sku: string;
    dateCreated: Date;
    isActive: boolean; 
  };
}
```

**Comment by rasienko** [comment]
Thanks for the great info, @sthielen ! I made some updates per your feedback. Please take another look and let me know if changes are required. One question, am I missing any attributes that can be defined in entitlements? E.g., `isConsumable` or any of the other `product` properties?

**Comment by sthielen** [comment]
Yes, there is both a boolean key `priceIsUnset`, which creates a product with no price (used in the donation/"pay what you want" template I made) and a `isConsumable` boolean key which allows a product to be purchased more than once (e.g., I can donate more than once, but I can't purchase the image unlock more than once because once it's been unlocked it's done).

**Comment by rasienko** [comment]
Great, thanks @sthielen ! Added this info. Please let me know if additional changes are required or if it's ready to merge. Thanks!

**Comment by sthielen** [comment]
Looks good to me!!

**Review by sthielen — APPROVED** [review]

**Pull request merged**
